import { useState } from "react";
import { Layout } from "@/components/layout/Layout";
import { Bot, Upload, Search, X, Loader2, User, Cpu } from "lucide-react";

interface Result {
  aiProbability: number;
  humanProbability: number;
  label: string;
  analysis: string;
  sentences: { text: string; isAI: boolean; confidence: number }[];
}

const AIDetector = () => {
  const [text, setText] = useState("");
  const [isChecking, setIsChecking] = useState(false);
  const [result, setResult] = useState<Result | null>(null);

  const handleCheck = async () => {
    if (!text.trim()) return;
    
    setIsChecking(true);
    setResult(null);
    
    try {
      const token = localStorage.getItem("token");
      const apiUrl = `http://${window.location.hostname}:5000/predict/ai`;
      const response = await fetch(apiUrl, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "Authorization": `Bearer ${token}`
        },
        body: JSON.stringify({ text }),
      });
      
      const data = await response.json();
      
      if (!response.ok || data.error) {
        throw new Error(data.error || "Failed to detect AI content");
      }
      
      setResult({
        aiProbability: data.aiProbability,
        humanProbability: data.humanProbability,
        label: data.label,
        sentences: (data.sentences || []).map((s: any) => ({
          text: s.text,
          isAI: s.isAI,
          confidence: Math.round(s.confidence),
        })),
        analysis: data.aiProbability > 50 
          ? "The text exhibits patterns typically associated with AI-generated content, including consistent sentence structure and predictable vocabulary usage."
          : "The text shows characteristics of human writing, including varied sentence structure and natural language flow.",
      });
    } catch (error: any) {
      console.error("Error checking text:", error);
      const apiUrl = `http://${window.location.hostname}:5000/predict/ai`;
      let errorMessage = error.message || "Error connecting to backend model.";
      if (errorMessage.includes("Failed to fetch")) {
        errorMessage = `Failed to connect to backend at ${apiUrl}. Please ensure the backend server is running on port 5000 and accessible from this machine.`;
      }
      alert(errorMessage);
    } finally {
      setIsChecking(false);
    }
  };

  const handleClear = () => {
    setText("");
    setResult(null);
  };

  return (
    <Layout>
      <div className="section-padding">
        <div className="container-custom">
          {/* Header */}
          <div className="max-w-3xl mx-auto text-center mb-12 animate-slide-up">
            <div className="inline-flex items-center justify-center w-16 h-16 rounded-2xl bg-purple-500/10 mb-6">
              <Bot className="w-8 h-8 text-purple-500" />
            </div>
            <h1 className="text-3xl md:text-4xl font-bold mb-4">
              AI Content Detector
            </h1>
            <p className="text-lg text-muted-foreground">
              Detect AI-generated content with high accuracy. Identify whether text
              was written by humans or generated by AI models like ChatGPT.
            </p>
          </div>

          {/* Main Content */}
          <div className="max-w-4xl mx-auto">
            <div className="bg-card rounded-2xl border border-border p-6 md:p-8 shadow-sm animate-fade-in">
              {/* Text Input */}
              <div className="mb-6">
                <div className="flex items-center justify-between mb-3">
                  <label className="font-medium">Enter text to analyze</label>
                  <span className="text-sm text-muted-foreground">
                    {text.split(/\s+/).filter(Boolean).length} words
                  </span>
                </div>
                <textarea
                  value={text}
                  onChange={(e) => setText(e.target.value)}
                  placeholder="Paste or type text here to detect if it was written by AI..."
                  className="input-field min-h-[250px] resize-y"
                />
              </div>

              {/* Actions */}
              <div className="flex flex-col sm:flex-row gap-3">
                <button
                  onClick={handleCheck}
                  disabled={!text.trim() || isChecking}
                  className="btn-primary flex-1 flex items-center justify-center gap-2 disabled:opacity-50"
                >
                  {isChecking ? (
                    <>
                      <Loader2 className="w-5 h-5 animate-spin" />
                      Analyzing...
                    </>
                  ) : (
                    <>
                      <Search className="w-5 h-5" />
                      Detect AI Content
                    </>
                  )}
                </button>
                
                <button
                  onClick={handleClear}
                  className="btn-secondary flex items-center justify-center gap-2"
                >
                  <X className="w-5 h-5" />
                  Clear
                </button>
                
                <label className="btn-secondary flex items-center justify-center gap-2 cursor-pointer">
                  <Upload className="w-5 h-5" />
                  Upload File
                  <input type="file" className="hidden" accept=".txt,.doc,.docx,.pdf" />
                </label>
              </div>
            </div>

            {/* Results */}
            {result && (
              <div className="mt-8 space-y-6 animate-slide-up">
                {/* Score Card */}
                <div className="bg-card rounded-2xl border border-border p-6 md:p-8">
                  <h3 className="text-lg font-semibold mb-6">Detection Results</h3>
                  
                  <div className="grid md:grid-cols-2 gap-6 mb-8">
                    {/* AI Score */}
                    <div className="p-6 rounded-xl bg-purple-500/5 border border-purple-500/20">
                      <div className="flex items-center gap-3 mb-4">
                        <div className="w-12 h-12 rounded-xl bg-purple-500/10 flex items-center justify-center">
                          <Cpu className="w-6 h-6 text-purple-500" />
                        </div>
                        <div>
                          <p className="text-sm text-muted-foreground">AI Generated</p>
                          <p className="text-3xl font-bold text-purple-500">{result.aiProbability}%</p>
                        </div>
                      </div>
                      <div className="h-2 rounded-full bg-secondary overflow-hidden">
                        <div 
                          className="h-full bg-purple-500 rounded-full transition-all duration-500"
                          style={{ width: `${result.aiProbability}%` }}
                        />
                      </div>
                    </div>

                    {/* Human Score */}
                    <div className="p-6 rounded-xl bg-green-500/5 border border-green-500/20">
                      <div className="flex items-center gap-3 mb-4">
                        <div className="w-12 h-12 rounded-xl bg-green-500/10 flex items-center justify-center">
                          <User className="w-6 h-6 text-green-500" />
                        </div>
                        <div>
                          <p className="text-sm text-muted-foreground">Human Written</p>
                          <p className="text-3xl font-bold text-green-500">{result.humanProbability}%</p>
                        </div>
                      </div>
                      <div className="h-2 rounded-full bg-secondary overflow-hidden">
                        <div 
                          className="h-full bg-green-500 rounded-full transition-all duration-500"
                          style={{ width: `${result.humanProbability}%` }}
                        />
                      </div>
                    </div>
                  </div>

                  {/* Analysis */}
                  <div className="p-4 rounded-xl bg-secondary/50">
                    <h4 className="font-medium mb-2">Conclusion</h4>
                    <p className="text-muted-foreground">
                      Based on the analysis, this text is <strong>{result.label}</strong>. 
                      ({result.humanProbability}% Human, {result.aiProbability}% AI). {result.analysis}
                    </p>
                  </div>
                </div>

                {/* Sentence Analysis */}
                <div className="bg-card rounded-2xl border border-border p-6 md:p-8">
                  <h3 className="text-lg font-semibold mb-6">Sentence-by-Sentence Analysis</h3>
                  
                  <div className="space-y-3">
                    {result.sentences.map((sentence, index) => (
                      <div
                        key={index}
                        className={`p-4 rounded-xl border ${
                          sentence.isAI 
                            ? 'bg-purple-500/5 border-purple-500/20' 
                            : 'bg-green-500/5 border-green-500/20'
                        }`}
                      >
                        <div className="flex items-start justify-between gap-4 mb-2">
                          <p className="text-sm">{sentence.text}</p>
                          <span className={`text-xs font-medium whitespace-nowrap px-2 py-1 rounded-full ${
                            sentence.isAI 
                              ? 'bg-purple-500/20 text-purple-500' 
                              : 'bg-green-500/20 text-green-500'
                          }`}>
                            {sentence.isAI ? 'AI' : 'Human'} ({sentence.confidence}%)
                          </span>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            )}
          </div>
        </div>
      </div>
    </Layout>
  );
};

export default AIDetector;
